### ISSUE TITLE
expected shape of image for realToComplex transform

### ISSUE THREAD

**Issue by psteinb** [imglib/imglib2-algorithm-fft#4]
hi,

I wanted to test-drive imglib2-algorithm-fft, but I am getting 

```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
        at net.imglib2.algorithm.fft2.FFTMethods.realToComplex(FFTMethods.java:580)
        at net.imglib2.algorithm.fft2.FFTMethods.realToComplex(FFTMethods.java:521)
        at net.imglib2.algorithm.fft2.FFTMethods.realToComplex(FFTMethods.java:473)
        at net.imglib2.algorithm.fft2.FFTMethods.realToComplex(FFTMethods.java:407)
...
```

The code I use goes along the lines of 

```
final ImgFactory< FloatType > imgFactory = new ArrayImgFactory< FloatType >();
final ImgFactory< ComplexFloatType > cimgFactory = new ArrayImgFactory< ComplexFloatType >();
	    
long[] shape = new long[] { 512, 512, 512 };
long[] cshape = new long[] { shape[0]/2 + 1, 512, 512 };
	    
final Img< FloatType > image = imgFactory.create( shape , new FloatType(0) );
final Img< ComplexFloatType > result = cimgFactory.create( cshape , new ComplexFloatType() );

final boolean flag = FFTMethods.realToComplex(image, result, shape.length);
```

I'd appreciate any help!

Best,
P

**Comment by bnorthan** [comment]
Hi @psteinb 

You might want to look at the FFT class.  It is higher level and sets up the Imgs for you.   For an example of how to use the FFT class you can look at this test.  (if you need to use the lower level FFTMethods you could follow the code in FFT to figure out how to set it up, if you step through the code you will notice the Imgs are extended using Views before calling FFTMethods)

https://github.com/imglib/imglib2-algorithm-fft/blob/master/src/test/java/net/imglib2/algorithm/fft2/FFTTest.java

```java
long[] dim = new long[] { i, i, i };

Img<FloatType> input =
				new ArrayImgFactory<FloatType>().create(dim, new FloatType());
placeSphereInCenter(input);

ImgFactory<ComplexFloatType> fftImgFactory = null;

try {
	fftImgFactory = input.factory().imgFactory(new ComplexFloatType());
}
catch (IncompatibleTypeException ex) {
	fftImgFactory = null;
}

Img<ComplexFloatType> fft = FFT.realToComplex(input, fftImgFactory);

Img<FloatType> inverse =
				input.factory().create(new FinalDimensions(dim), new FloatType());
FFT.complexToRealUnpad(fft, inverse);

assertImagesEqual(input, inverse, 0.00001f);
```

**Comment by psteinb** [comment]
hi @bnorthan ,

bloody me, I am wandering the web and the answer is in front of me. thanks a bunch!
btw, what is the try-catch cause for?

**Comment by psteinb** [comment]
also, are these imports really required?
https://github.com/imglib/imglib2-algorithm-fft/blob/master/src/main/java/net/imglib2/algorithm/fft2/FFTMethods.java#L53
https://github.com/imglib/imglib2-algorithm-fft/blob/master/src/main/java/net/imglib2/algorithm/fft2/FFTMethods.java#L54
or in other words does imglib2-algorithm-fft really have a dependency on edu.mines.jtk.dsp.*?

**Comment by ctrueden** [comment]
@psteinb There is a dependency on Mines JTK on master at the moment, but we are migrating away from it toward JTransform, thanks to @bnorthan's hard work. See https://github.com/imglib/imglib2-algorithm-fft/pull/3 and https://github.com/imglib/imglib2/issues/61.

**Comment by bnorthan** [comment]
@psteinb input.factory().imgFactory() can throw an IncompatibleTypeException, and the code won't compile without the try/catch. 

This was a test so the type (ComplexFloatType) was hard coded.  But the type can also be passed in as a variable (ie maybe we don't know if we want ComplexFloatType or ComplexDoubleType, so we leave it up to the caller).  So in that case the type could be incompatible and we need to handle the potential error.

**Comment by psteinb** [comment]
hi guys,
thank you for the hard work and getting back to me so quickly. I got it running after including the jtk.jar (for now). 
+1

**Comment by ctrueden** [comment]
@psteinb Note that if you use Maven, you only need to add a dependency block like:
```xml
<dependency>
  <groupId>net.imglib2</groupId>
  <artifactId>imglib2-algorithm-fft</artifactId>
  <version>LATEST</version>
</dependency>
```
And then transitive dependencies are pulled in automatically. Saves a lot of pain. (Though using `LATEST` is a two-edged sword; you might want to instead pin to a stable release version like `0.1.1`.)
